<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Echoes_of_Aurora</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="assets\*.obj" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
